# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af955fe755967af3f8bc9a39e13ad1d5"
name = "Delifast Public"
application_url = "https://delifast-public.onrender.com"
embedded = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "https://delifast-public.onrender.com/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_fulfillments,write_fulfillments,read_orders,write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://delifast-public.onrender.com/auth/callback",
  "https://delifast-public.onrender.com/auth/login"
]
